import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/components/providers/providers";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { Toaster } from "@/components/ui/sonner"
import { DM_Sans, Playfair_Display } from 'next/font/google'

const _dmSans = DM_Sans({ subsets: ["latin"], variable: '--font-dm-sans' });
const _playfair = Playfair_Display({ subsets: ["latin"], variable: '--font-playfair' });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className="antialiased font-sans"
      >
        <Providers>
          <Header />
          <main className="">
            {children}
          </main>
          <Footer />
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
